---
name: PR

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  FORCE_COLOR: "1"
  PYTHON_LATEST: "3.10"

jobs:
  package:
    name: Build and verify package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_LATEST }}

      - run: python -m pip install --upgrade twine build check-wheel-contents
      - run: python -m build --sdist --wheel .
      - run: check-wheel-contents dist/*.whl
      - run: python -m twine check dist/*
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
